load('scat_k300_Nsds.mat'); 
imagesc(Ns, ds, log10(err')); colorbar; caxis([-10 0]); colorbar; set(gca, 'FontSize', 16); axis xy;
colormap jet; 
title('err vs N,d when k = 300'); 
xlabel('N'); 
ylabel('d'); 
saveas(gcf, 'k300_Nsds.eps', 'epsc2');

figure; 
load('scat_k30.mat'); 
semilogy(Ns, err, 'LineWidth', 1.5); set(gca, 'FontSize', 16); 
title('err vs N when k = 30'); 
figure; 
plot(Ns, ts', 'LineWidth', 1.5); set(gca, 'FontSize', 16); 
title('t(s) vs N when k = 30'); 

figure; 
load('scat_k300.mat'); 
semilogy(Ns, err, 'LineWidth', 1.5); set(gca, 'FontSize', 16); 
title('err vs N when k = 300 at d = 0.012'); 
saveas(gcf, 'k300_err_vs_N.eps', 'epsc2');
xlabel('N'); 
ylabel('err'); 
figure; 
plot(Ns, ts', 'LineWidth', 1.5); set(gca, 'FontSize', 16); 
title('t(s) vs N when k = 300 at d = 0.012');
xlabel('N'); 
ylabel('t'); 
saveas(gcf, 'k300_t_vs_N.eps', 'epsc2');

figure; 
load('scat_k3000.mat');
semilogy(Ns, err, 'LineWidth', 1.5); set(gca, 'FontSize', 16); 
title('err vs N when k = 3000'); 
figure; 
plot(Ns, ts', 'LineWidth', 1.5); set(gca, 'FontSize', 16); 
title('t(s) vs N when k = 3000'); 

figure; 
load('scat_N1e5_ks.mat'); 
semilogy(ks, err, 'LineWidth', 1.5); set(gca, 'FontSize', 16); 
title('err vs k when N = 1e5 at d = 0.012'); 
xlabel('N'); 
ylabel('t'); 
saveas(gcf, 'N1e5_err_vs_k.eps', 'epsc2');
figure; 
plot(ks, ts', 'LineWidth', 1.5); set(gca, 'FontSize', 16); 
title('t(s) vs N when N = 1e5 at d = 0.012'); 
xlabel('k'); 
ylabel('t'); 
saveas(gcf, 'N1e5_t_vs_k.eps', 'epsc2');